### PR TITLE
wiseconnect: Add DMA driver

### PR DESCRIPTION
**Pull request by smalae**
Origin: Silicon Labs WiSeConnect SDK
License: MSLA
URL: https://github.com/siliconlabs/wiseconnect
Commit: e97a0ed00ddda347a8a39e8276f470e1c5fea469
Version: 3.3
Purpose: Add DMA support for SiWx917

### CODE REVIEW

**Comment by jerome-pouiller** [comment]
> Version: 3.4
For now, `hal_silabs` uses wiseconnect 3.3. I believe it is a bad idea to mix the wiseconnect versions.

**Comment by jerome-pouiller** [comment]
Could you split this commit in two parts:
  - raw import of the wiseconnect files
  - compilation and other fixes
 Thus, when we will upgrade wiseconnect, we know what changes need to be be ported.

**Comment by smalae** [comment]
> Could you split this commit in two parts:
> 
> * raw import of the wiseconnect files
> * compilation and other fixes
>   Thus, when we will upgrade wiseconnect, we know what changes need to be be ported.

I updated the files from 3.3.0, and everything seems to be fine. The warnings that I am getting are due to the version mismatch between rsi_rom_table_si91x.h and rsi_rom_udma_wrapper.h files. rsi_rom_udma_wrapper.h file is updated somewhere in the 3.3.2/3.3.1 release. Maintaining the same version, 3.3.0, resolved the issue.

**Comment by jerome-pouiller** [comment]
The description of the origin of the files should go in the commit log. BTW, `35948a2` does not exist in `https://github.com/SiliconLabs/wiseconnect/`. You probably mean `e97a0ed00ddda347a8a39e8276f470e1c5fea469`.

**Pull request merged**
