### PR TITLE
wiseconnect: Fix clock init

### PR DESCRIPTION
**Pull request by asmellby**
Add common flash config, which is required to get access to calibration values during init.

Add clock manager to enable core clock to use 180 MHz PLL. Clock manager depends on GSDK/SiSDK sl_status.h, hence the include path into the gecko directory.

### CODE REVIEW

**Review by jhedberg — APPROVED** [review]

**Comment by jhedberg** [comment]
@asmellby I assume you're preparing a corresponding PR to zephyr-silabs as well? You should be able to temporarily reference this PR from there (in west.yml) to demonstrate that CI will pass with the combination before merging this PR.

**Comment by jhedberg** [comment]
> @asmellby I assume you're preparing a corresponding PR to zephyr-silabs as well? You should be able to temporarily reference this PR from there (in west.yml) to demonstrate that CI will pass with the combination before merging this PR.

https://docs.zephyrproject.org/latest/develop/modules.html#process-for-submitting-changes-to-existing-modules

**Comment by asmellby** [comment]
https://github.com/SiliconLabsSoftware/zephyr-silabs/pull/28 seems to have passed with these changes.

**Comment by jerome-pouiller** [comment]
In fact, sl_status is available in `./components/device/stm32/silabs_utility/common/inc/sl_status.h`. I would prefer to avoid cross-references between gecko_sdk, si_sdk and wiseconnect if possible.

**Comment by asmellby** [comment]
> In fact, sl_status is available in `./components/device/stm32/silabs_utility/common/inc/sl_status.h`. I would prefer to avoid cross-references between gecko_sdk, si_sdk and wiseconnect if possible.

That's a copy used for cross-platform host stuff. We are going to need a lot more of the GSDK going forward -- wiseconnect is an SDK extension that does depend on base GSDK content -- particularly API headers, such as `sl_sleeptimer.h`. So I don't see a good reason to use the STM32 copy of sl_status.h, we're going to need the one from the GSDK at some point anyway.

**Comment by jerome-pouiller** [comment]
I see. So, we should avoid to import in WiseConnect any file/API already provided by GeckoSDK/SiSDK (like sl_status.h), that's it? I will change my local work to comply with this rule.

For now, I assume we don't have to worry about possible API breakage between WiseConnect and GeckoSDK. If WiseConnect imports only well identified headers, I don't see too many risks.

**Pull request merged**
