### PR TITLE
modules: hal_silabs: introduce WiSeConnect SDK

### PR DESCRIPTION
**Pull request by jerome-pouiller**

### CODE REVIEW

**Review by asmellby — DISMISSED** [review]
IMO the commit message needs to contain origin information, as described in https://docs.zephyrproject.org/latest/contribute/guidelines.html#identifying-contribution-origin

**Comment by jerome-pouiller** [comment]
> IMO the commit message needs to contain origin information, as described in https://docs.zephyrproject.org/latest/contribute/guidelines.html#identifying-contribution-origin

Definitely.

**Comment by jerome-pouiller** [comment]
v2:
  - Add origin information to commit message

**Comment by asmellby** [comment]
I just realized that this is targeted at the master branch. Should we stage it on a feature branch for 917 for now? We will need to bottom out relicensing of a lot of these files before this can be upstreamed, MSLA is not OK there AFAIK.

We could of course merge to master early, but that will effectively temporarily hard-fork us until the licensing is resolved.

**Comment by jerome-pouiller** [comment]
I think we have a bit of time in front of us to rename the master branch if we need. I believe we don't need to bother with that now.

**Comment by asmellby** [comment]
I meant it more in the sense that if we make any EFR32 changes upstream, they can't be synced back here if we have "stolen" the main branch name to use for the 917 work. The branch in this fork with corresponding name to the branch upstream shouldn't differ from upstream IMO.

**Comment by jhedberg** [comment]
> I meant it more in the sense that if we make any EFR32 changes upstream, they can't be synced back here if we have "stolen" the main branch name to use for the 917 work. The branch in this fork with corresponding name to the branch upstream shouldn't differ from upstream IMO.

Yes. This makes sense. Since we're treating this internal tree as a downstream tree, it'd be better to keep existing upstream branches (like `master`) untouched and in sync with upstream.

Kind of related: we need to do a `master` -> `main` rename to be in line with the general naming conventions of upstream module trees as well as https://docs.zephyrproject.org/latest/contribute/coding_guidelines/index.html#rule-a-2-inclusive-language

**Comment by jerome-pouiller** [comment]
v3:
  * fix compile definitions. This fix most of the issues with clocks and JTag.

**Comment by jerome-pouiller** [comment]
> Yes. This makes sense. Since we're treating this internal tree as a downstream tree, it'd be better to keep existing upstream branches (like `master`) untouched and in sync with upstream.

What name do you want to use: `sl-main`, `silabs`, `siwx917`, or ...?

> Kind of related: we need to do a `master` -> `main` rename to be in line with the general naming conventions of upstream module trees as well as https://docs.zephyrproject.org/latest/contribute/coding_guidelines/index.html#rule-a-2-inclusive-language

I don't have the privilege to change that on `zephyrproject-rtos/hal_silabs`. Maybe you have?

**Comment by jhedberg** [comment]
> What name do you want to use: `sl-main`, `silabs`, `siwx917`, or ...?

I think that depends on the purpose. If it's going to be for a specific project/product then something like `siwx917` makes sense, however if it's going to be a general purpose downstream development branch then `silabs` or `silabs-dev` would be ok.

> I don't have the privilege to change that on `zephyrproject-rtos/hal_silabs`. Maybe you have?

I should. Let me check.

**Comment by jhedberg** [comment]
> > I don't have the privilege to change that on `zephyrproject-rtos/hal_silabs`. Maybe you have?
> 
> I should. Let me check.

Done.

**Review by jhedberg — APPROVED** [review]

**Pull request merged**
