### PR TITLE
Cherry pick main

### PR DESCRIPTION
**Pull request by jerome-pouiller**
This PR cherry-picks the commits existing on upstream of `hal_silabs`. The result is now:

```
$ git range-diff upstream/main...cherry-pick-main
 -:  ------- >  1:  65ae59c modules: hal_silabs: introduce WiSeConnect SDK
 -:  ------- >  2:  c21ab6d modules: hal_silabs: fix missing si91x_mvp.h file
 -:  ------- >  3:  c405570 wiseconnect: Add common flash mode config
 -:  ------- >  4:  568c306 wiseconnect: Add clock manager
 -:  ------- >  5:  3994a00 wiseconnect: Add gpio driver
 -:  ------- >  6:  7c279c3 gecko: Import sl_bit.h and sl_string.h
 -:  ------- >  7:  e19bea2 wiseconnect: Add WiFi components of WiSeConnect SDK
 -:  ------- >  8:  2f4e442 wiseconnect: Fix conflict with Zephyr definition of "fd_set"
 -:  ------- >  9:  4c8b690 wiseconnect: Apply changes to WiseConnect
 -:  ------- > 10:  de01213 wiseconnect: Fix compiler warning
 -:  ------- > 11:  3febda5 wiseconnect: Fix memory access in sli_si91x_accept_async()
 -:  ------- > 12:  c1fcd06 wiseconnect: Enable IPv6
 -:  ------- > 13:  60b9211 wiseconnect: Add Bluetooth HCI driver
 -:  ------- > 14:  7279733 wiseconnect: BLE and WiFi related SDK patches
 -:  ------- > 15:  1e8a139 wiseconnect: CONFIG_SIWX917_NWP_NETWORK_STACK rename to CONFIG_WISECONNECT_NETWORK_STACK
 1:  8655b38 = 16:  be64eca simplicity_sdk: Add script to import new HAL
 2:  f9e34f1 = 17:  99e94f1 simplicity_sdk: Import HAL files from Simplicity SDK
 3:  92a182a = 18:  cdc2ec1 simplicity_sdk: Apply minor patches to work with Zephyr
 4:  ffe6987 ! 19:  9872839 simplicity_sdk: Make use of HAL for Series 2
    @@ .gitignore

      ## CMakeLists.txt ##
     @@
    + # Copyright (c) 2024 Silicon Laboratories Inc.
    + # SPDX-License-Identifier: Apache-2.0
    +
     -add_subdirectory_ifdef(CONFIG_HAS_SILABS_GECKO gecko)
     +add_subdirectory_ifdef(CONFIG_SOC_FAMILY_SILABS_S0 gecko)
     +add_subdirectory_ifdef(CONFIG_SOC_FAMILY_SILABS_S1 gecko)
     +add_subdirectory_ifdef(CONFIG_SOC_FAMILY_SILABS_S2 simplicity_sdk)
      add_subdirectory_ifdef(CONFIG_HAS_SILABS_GECKO zephyr)
      add_subdirectory_ifdef(CONFIG_HAS_SILABS_SI32 si32)
    +

      ## simplicity_sdk/CMakeLists.txt (new) ##
     @@
 5:  3ce3730 = 20:  2ae886b zephyr: Add allocation API shim for SiSDK memory manager
 6:  bb44c61 = 21:  d314129 gecko: Remove Series 2 support
 7:  1b1fa32 = 22:  863321d gecko: Remove unused CMSIS startup files
 8:  d07d744 = 23:  87cfea1 zephyr: drivers: move Link Layer glue component to HCI driver
 9:  90258fb = 24:  d063938 scripts: Clock control header generation script
```

### CODE REVIEW

**Comment by jhedberg** [comment]
I guess we have three ways of introducing changes from upstream:

 - upmerge (git merge)
 - rebase
 - cherrypick (what you've done)

Does cherrypicking come with any downsides (one upside is at least that it won't break old references to the HAL tree)? E.g. is there a chance that git might not be able to be as smart about doing a rebase operation in the future?

**Comment by jerome-pouiller** [comment]
`git range-diff` shows there is small divergence on `CMakeLists.txt`. Outside that, no I don't think `git rebase` could fail (I don't know the detail of how `git` detect when a patch is already applied, but I assume it the same than `git range-diff`).

**Comment by jerome-pouiller** [comment]
BTW, `git merge` will also continue to work

**Review by jhedberg — APPROVED** [review]
Ok, then I'm fine with these changes. Were you planning on merging this before fixing the incorrect PR HEAD reference in zephyr-silabs?

**Comment by jhedberg** [comment]
@jerome-pouiller feel free to merge this one and fix up west.yml in zephyr-silabs. Note that you should *not* delete this PR's branch before west.yml has been fixed, since otherwise we'll start getting failing CI workflows.

**Pull request merged**
